### ISSUE TITLE
Blocker w/ JDK to 8u161

### ISSUE THREAD

**Issue by lmangani** [strapdata/elassandra#162]
Core Cassandra presently have JMX/RMI issues due to breaking changes in JDK to 8u161
There seems to be no workaround at the moment pending a core patch propagation - the latest Elassandra builds including 5.5.0.9, 5.5.0.10 are affected.

Not an Elassandra issue if not indirectly, so I'm raising this purely for tracking and sharing w/ other users; 
Original Issue: https://issues.apache.org/jira/browse/CASSANDRA-14173

**Comment by vroyer** [comment]
Will be corrected when cassandra 3.11.2 will be released.

**Comment by davidlar** [comment]
3.11.2 is released....

**Comment by vroyer** [comment]
Yes, release candidate with cassandra 3.11.2 is available here https://github.com/strapdata/elassandra5-rc/releases/tag/v5.5.0.13

**Comment by davidlar** [comment]
Great!

**Comment by vroyer** [comment]
Fixed with release 5.5.0.13+ and upgrade to cassandra-3.11.2

**Comment by ssnigorovskyi** [comment]
3.11.2 still not working with JMX explorer, it makes cassandra 3.11.2 not working after start, 3.11 was work fine
