### ISSUE TITLE
Returning data into consistent format

### ISSUE THREAD

**Issue by silviucpp** [strapdata/elassandra#279]
Hello,

Not sure if we can call this "bug" but here is the problem:

If you have a table using "inet" and "timestamp" data types, when query via cassandra the results are returned as :

timestamp - unix timestamp in ms
inet - string, example : "127.0.0.1"

query same values via ELS:

timestamp - returned as ISO8601
inet - returned as string but appends "/" in front, example: "/127.0.01"

Any way I can do something to have consistent formatting (other than handle-ing this into the code)

Silviu

**Comment by vroyer** [comment]
Hi,

For timestamps, you can set a date format, ISO is the default, see https://www.elastic.co/guide/en/elasticsearch/reference/6.2/mapping-date-format.html#strict-date-time <https://www.elastic.co/guide/en/elasticsearch/reference/6.2/mapping-date-format.html#strict-date-time>
For Ip address, it’s a bug (InetAddress.toString() instead of InetAddress.getHostAddress()).
This will be fixed in the next release available next week.
Thanks.
Vincent.

**Comment by silviucpp** [comment]
Hello, I tried to set it to `epoch_millis` but has no effect. I created the index as :

```sh
curl -XPUT "http://172.17.33.171:9200/index_name" -H 'Content-Type: application/json' -d '
{
    "settings" : { "keyspace" : "test" },
    "mappings": {
        "users": {
            "_field_names": {"enabled": false},
            "discover": ".*",
            "properties": {
                "created_at":{
                    "index": false,
                    "format" : "epoch_millis"
                }
            }
        }
   }
}'
```
I'm missing something ?

Silviu

**Comment by vroyer** [comment]
You're right, output format was no use to build the _source document.
This is fixed in the last release 6.2.3.14.
Thanks for reporting the issue.

**Comment by silviucpp** [comment]
Hello the bug seems partially fixed. 

The example I provided above the `timestamp` field is now returned in milliseconds but as string:

 `"created_at": "1539783087034"`, instead  `"created_at": 1539783087034`

Any idea ?

Silviu

**Comment by silviucpp** [comment]
Hello @vroyer ,

any thought on this ?

Silviu

**Comment by vroyer** [comment]
Elasticsearch store the source document as you insert it, but elassandra rebuild the source document from the cassandra table, and it use the date format to generate the date representation as string, even when the result date format is a number. You can directly access that field as a long through CQL without using the _source document.

**Comment by silviucpp** [comment]
Ok in case nothing can be done here I'll close the issue
